config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'

  resources :docs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc.rb
class Doc < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :docs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController

  before_action :find_doc, only: [:show, :edit, :update, :destroy]

  def index
    @docs = Doc.all.order("created_at DESC")
  end

  def show

  end

  def new
    @doc = current_user.docs.build
  end

  def create
    @doc = current_user.docs.build(doc_params)

    if @doc.save
      redirect_to @doc
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @doc.update(doc_params)
      redirect_to @doc
    else
      render 'update'
    end
  end

  def destroy
    @doc.destroy
    redirect_to docs_path
  end

  private

    def find_doc
      @doc = Doc.find(params[:id])
    end

    def doc_params
      params.require(:doc).permit(:title, :content)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/_form.html.erb
<%= simple_form_for @doc do |f| %>
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.button :submit %>
<% end %>

app/views/docs/edit.html.erb
<h1> Edit Doc!</h1>

<%= render 'form' %>

<%= link_to "Cancel & Go Back", doc_path %>

app/views/docs/index.html.erb
<h1>View All Docs</h1>

<% @docs.each do |doc| %>
  <h2><%= link_to doc.title, doc %></h2>
  <p>Created <%= time_ago_in_words(doc.created_at) %> ago</p>
  <p> <%= truncate(doc.content, length: 30) %></p>
<% end %>

<%= link_to "Create Doc", new_doc_path %>

app/views/docs/new.html.erb
<h1>New Doc!</h1>

<%= render 'form' %>

app/views/docs/show.html.erb
<h1><%= @doc.title %></h1>

<p><%= @doc.content %></p>

<%= link_to "All Docs", docs_path %>
<%= link_to "Fix Doc", edit_doc_path(@doc) %>
<%= link_to "Delete Doc", doc_path(@doc), method: :delete, data: { confirm: "Are you sure you want to delete this doc?"} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Uploader</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.haml
<h1>Voila! Welcome to my Uploader project homepage</h1>